var v = {
  zh: {
    AI: 'AI',
    'Internet connected?': '网络已连接？',
    'Create a new chat with id[ID]': '创建ID为[ID]的新聊天',
    'Delete chat with id[ID]': '删除ID为[ID]的聊天',
    'Clear all chats': '清空所有聊天',
    'Create a new AI preset with id [ID]': '创建ID为[ID]的新AI预设',
    'Delete AI preset with id [ID]': '删除ID为[ID]的AI预设',
    'Clear all AI presets': '清空所有AI预设',
    'Set the [PROP] of AI preset [ID] to [VALUE]': '将AI预设 [ID] 的 [PROP] 设置为 [VALUE]',
    'Use AI preset [PRESET_ID] for chat [CHAT_ID]': '为聊天 [CHAT_ID] 使用AI预设 [PRESET_ID]',
    'Set request format for preset with id[ID] to [FORMAT]':
      '将ID为[ID]的预设的请求格式设置为 [FORMAT]',
    'Send message [MESSAGE] to chat with id[ID]': '向ID为[ID]的聊天发送消息 [MESSAGE]',
    'Stop message from chat [ID]': '停止聊天 [ID] 的消息',
    'Response from chat [ID]': '聊天 [ID] 的响应',
    'Status of chat with id[ID]': 'ID为[ID]的聊天状态',
    'Is chat with id[ID] idle?': 'ID为[ID]的聊天是否空闲？',
    'Common AI': '常用AI',
    'URL of [AI](Anthropic)': '[AI]的URL(Anthropic)',
    'URL of [AI](OpenAI)': '[AI]的URL(OpenAI)',
    'Data processing(JSON)': '数据处理(JSON)',
    'Overwrite id[ID] in [MAP] with JSON [DATA]': '用JSON [DATA] 覆盖 [MAP] 中的ID [ID]',
    'Overwrite chat history of id[ID] with JSON [DATA]': '用JSON [DATA] 覆盖ID为[ID]的聊天历史',
    'Clear chat history of id[ID]': '清空ID为[ID]的聊天历史',
    'Add a message to chat [ID] with role[ROLE] and content[CONTENT]':
      '向聊天 [ID] 添加角色为[ROLE]内容为[CONTENT]的消息',
    'Delete message at index [INDEX] from chat with id[ID]':
      '从ID为[ID]的聊天中删除索引为 [INDEX] 的消息',
    'Cover [DIFF] to [BASE]': '将 [DIFF] 覆盖到 [BASE]',
    "Set [OBJECT]'s [KEY] to [VALUE]": '将 [OBJECT] 的 [KEY] 设置为 [VALUE]',
    'All keys of [MAP]': '[MAP] 的所有键',
    'Data of [ID] from [MAP]': '[MAP] 中 [ID] 的数据',
    'Chat history from id[ID]': 'ID为[ID]的聊天历史',
    '[PROP] of item [INDEX] of chat history id[ID]': '聊天历史ID[ID]中第 [INDEX] 项的 [PROP]',
    'Length of [ARRAY]': '[ARRAY] 的长度',
    'Item [INDEX] of array[ARRAY]': '数组[ARRAY]的第 [INDEX] 项',
    'Item [KEY] of object[OBJECT]': '对象[OBJECT]的 [KEY] 项',
    Chats: '聊天',
    'AI presets': 'AI预设',
    'API Key': 'API密钥',
    'Request URL': '请求URL',
    Model: '模型',
    role: '角色',
    content: '内容',
    user: '用户',
    assistant: '助手',
    chat1: '聊天1',
    preset1: '预设1',
    Hello: '你好',
    'How do you do?': '你好吗？',
    key1: '键1',
    '"value1"': '"值1"',
  },
  'zh-cn': {
    AI: 'AI',
    'Internet connected?': '网络已连接？',
    'Create a new chat with id[ID]': '创建ID为[ID]的新聊天',
    'Delete chat with id[ID]': '删除ID为[ID]的聊天',
    'Clear all chats': '清空所有聊天',
    'Create a new AI preset with id [ID]': '创建ID为[ID]的新AI预设',
    'Delete AI preset with id [ID]': '删除ID为[ID]的AI预设',
    'Clear all AI presets': '清空所有AI预设',
    'Set the [PROP] of AI preset [ID] to [VALUE]': '将AI预设 [ID] 的 [PROP] 设置为 [VALUE]',
    'Use AI preset [PRESET_ID] for chat [CHAT_ID]': '为聊天 [CHAT_ID] 使用AI预设 [PRESET_ID]',
    'Set request format for preset with id[ID] to [FORMAT]':
      '将ID为[ID]的预设的请求格式设置为 [FORMAT]',
    'Send message [MESSAGE] to chat with id[ID]': '向ID为[ID]的聊天发送消息 [MESSAGE]',
    'Stop message from chat [ID]': '停止聊天 [ID] 的消息',
    'Response from chat [ID]': '聊天 [ID] 的响应',
    'Status of chat with id[ID]': 'ID为[ID]的聊天状态',
    'Is chat with id[ID] idle?': 'ID为[ID]的聊天是否空闲？',
    'Common AI': '常用AI',
    'URL of [AI](Anthropic)': '[AI]的URL(Anthropic)',
    'URL of [AI](OpenAI)': '[AI]的URL(OpenAI)',
    'Data processing(JSON)': '数据处理(JSON)',
    'Overwrite id[ID] in [MAP] with JSON [DATA]': '用JSON [DATA] 覆盖 [MAP] 中的ID [ID]',
    'Overwrite chat history of id[ID] with JSON [DATA]': '用JSON [DATA] 覆盖ID为[ID]的聊天历史',
    'Clear chat history of id[ID]': '清空ID为[ID]的聊天历史',
    'Add a message to chat [ID] with role[ROLE] and content[CONTENT]':
      '向聊天 [ID] 添加角色为[ROLE]内容为[CONTENT]的消息',
    'Delete message at index [INDEX] from chat with id[ID]':
      '从ID为[ID]的聊天中删除索引为 [INDEX] 的消息',
    'Cover [DIFF] to [BASE]': '将 [DIFF] 覆盖到 [BASE]',
    "Set [OBJECT]'s [KEY] to [VALUE]": '将 [OBJECT] 的 [KEY] 设置为 [VALUE]',
    'All keys of [MAP]': '[MAP] 的所有键',
    'Data of [ID] from [MAP]': '[MAP] 中 [ID] 的数据',
    'Chat history from id[ID]': 'ID为[ID]的聊天历史',
    '[PROP] of item [INDEX] of chat history id[ID]': '聊天历史ID[ID]中第 [INDEX] 项的 [PROP]',
    'Length of [ARRAY]': '[ARRAY] 的长度',
    'Item [INDEX] of array[ARRAY]': '数组[ARRAY]的第 [INDEX] 项',
    'Item [KEY] of object[OBJECT]': '对象[OBJECT]的 [KEY] 项',
    Chats: '聊天',
    'AI presets': 'AI预设',
    'API Key': 'API密钥',
    'Request URL': '请求URL',
    Model: '模型',
    role: '角色',
    content: '内容',
    user: '用户',
    assistant: '助手',
    chat1: '聊天1',
    preset1: '预设1',
    Hello: '你好',
    'How do you do?': '你好吗？',
    key1: '键1',
    '"value1"': '"值1"',
  },
  'zh-tw': {
    AI: 'AI',
    'Internet connected?': '網路已連接？',
    'Create a new chat with id[ID]': '建立ID為[ID]的新聊天',
    'Delete chat with id[ID]': '刪除ID為[ID]的聊天',
    'Clear all chats': '清空所有聊天',
    'Create a new AI preset with id [ID]': '建立ID為[ID]的新AI預設',
    'Delete AI preset with id [ID]': '刪除ID為[ID]的AI預設',
    'Clear all AI presets': '清空所有AI預設',
    'Set the [PROP] of AI preset [ID] to [VALUE]': '將AI預設 [ID] 的 [PROP] 設定為 [VALUE]',
    'Use AI preset [PRESET_ID] for chat [CHAT_ID]': '為聊天 [CHAT_ID] 使用AI預設 [PRESET_ID]',
    'Set request format for preset with id[ID] to [FORMAT]':
      '將ID為[ID]的預設的請求格式設定為 [FORMAT]',
    'Send message [MESSAGE] to chat with id[ID]': '向ID為[ID]的聊天傳送訊息 [MESSAGE]',
    'Stop message from chat [ID]': '停止聊天 [ID] 的訊息',
    'Response from chat [ID]': '聊天 [ID] 的回應',
    'Status of chat with id[ID]': 'ID為[ID]的聊天狀態',
    'Is chat with id[ID] idle?': 'ID為[ID]的聊天是否空閒？',
    'Common AI': '常用AI',
    'URL of [AI](Anthropic)': '[AI]的URL(Anthropic)',
    'URL of [AI](OpenAI)': '[AI]的URL(OpenAI)',
    'Data processing(JSON)': '資料處理(JSON)',
    'Overwrite id[ID] in [MAP] with JSON [DATA]': '用JSON [DATA] 覆蓋 [MAP] 中的ID [ID]',
    'Overwrite chat history of id[ID] with JSON [DATA]': '用JSON [DATA] 覆蓋ID為[ID]的聊天歷史',
    'Clear chat history of id[ID]': '清空ID為[ID]的聊天歷史',
    'Add a message to chat [ID] with role[ROLE] and content[CONTENT]':
      '向聊天 [ID] 新增角色為[ROLE]內容為[CONTENT]的訊息',
    'Delete message at index [INDEX] from chat with id[ID]':
      '從ID為[ID]的聊天中刪除索引為 [INDEX] 的訊息',
    'Cover [DIFF] to [BASE]': '將 [DIFF] 覆蓋到 [BASE]',
    "Set [OBJECT]'s [KEY] to [VALUE]": '將 [OBJECT] 的 [KEY] 設定為 [VALUE]',
    'All keys of [MAP]': '[MAP] 的所有鍵',
    'Data of [ID] from [MAP]': '[MAP] 中 [ID] 的資料',
    'Chat history from id[ID]': 'ID為[ID]的聊天歷史',
    '[PROP] of item [INDEX] of chat history id[ID]': '聊天歷史ID[ID]中第 [INDEX] 項的 [PROP]',
    'Length of [ARRAY]': '[ARRAY] 的長度',
    'Item [INDEX] of array[ARRAY]': '陣列[ARRAY]的第 [INDEX] 項',
    'Item [KEY] of object[OBJECT]': '物件[OBJECT]的 [KEY] 項',
    Chats: '聊天',
    'AI presets': 'AI預設',
    'API Key': 'API金鑰',
    'Request URL': '請求URL',
    Model: '模型',
    role: '角色',
    content: '內容',
    user: '使用者',
    assistant: '助手',
    chat1: '聊天1',
    preset1: '預設1',
    Hello: '你好',
    'How do you do?': '你好嗎？',
    key1: '鍵1',
    '"value1"': '"值1"',
  },
  en: {
    AI: 'AI',
    'Internet connected?': 'Internet connected?',
    'Create a new chat with id[ID]': 'Create a new chat with id[ID]',
    'Delete chat with id[ID]': 'Delete chat with id[ID]',
    'Clear all chats': 'Clear all chats',
    'Create a new AI preset with id [ID]': 'Create a new AI preset with id [ID]',
    'Delete AI preset with id [ID]': 'Delete AI preset with id [ID]',
    'Clear all AI presets': 'Clear all AI presets',
    'Set the [PROP] of AI preset [ID] to [VALUE]': 'Set the [PROP] of AI preset [ID] to [VALUE]',
    'Use AI preset [PRESET_ID] for chat [CHAT_ID]': 'Use AI preset [PRESET_ID] for chat [CHAT_ID]',
    'Set request format for preset with id[ID] to [FORMAT]':
      'Set request format for preset with id[ID] to [FORMAT]',
    'Send message [MESSAGE] to chat with id[ID]': 'Send message [MESSAGE] to chat with id[ID]',
    'Stop message from chat [ID]': 'Stop message from chat [ID]',
    'Response from chat [ID]': 'Response from chat [ID]',
    'Status of chat with id[ID]': 'Status of chat with id[ID]',
    'Is chat with id[ID] idle?': 'Is chat with id[ID] idle?',
    'Common AI': 'Common AI',
    'URL of [AI](Anthropic)': 'URL of [AI](Anthropic)',
    'URL of [AI](OpenAI)': 'URL of [AI](OpenAI)',
    'Data processing(JSON)': 'Data processing(JSON)',
    'Overwrite id[ID] in [MAP] with JSON [DATA]': 'Overwrite id[ID] in [MAP] with JSON [DATA]',
    'Overwrite chat history of id[ID] with JSON [DATA]':
      'Overwrite chat history of id[ID] with JSON [DATA]',
    'Clear chat history of id[ID]': 'Clear chat history of id[ID]',
    'Add a message to chat [ID] with role[ROLE] and content[CONTENT]':
      'Add a message to chat [ID] with role[ROLE] and content[CONTENT]',
    'Delete message at index [INDEX] from chat with id[ID]':
      'Delete message at index [INDEX] from chat with id[ID]',
    'Cover [DIFF] to [BASE]': 'Cover [DIFF] to [BASE]',
    "Set [OBJECT]'s [KEY] to [VALUE]": "Set [OBJECT]'s [KEY] to [VALUE]",
    'All keys of [MAP]': 'All keys of [MAP]',
    'Data of [ID] from [MAP]': 'Data of [ID] from [MAP]',
    'Chat history from id[ID]': 'Chat history from id[ID]',
    '[PROP] of item [INDEX] of chat history id[ID]':
      '[PROP] of item [INDEX] of chat history id[ID]',
    'Length of [ARRAY]': 'Length of [ARRAY]',
    'Item [INDEX] of array[ARRAY]': 'Item [INDEX] of array[ARRAY]',
    'Item [KEY] of object[OBJECT]': 'Item [KEY] of object[OBJECT]',
    Chats: 'Chats',
    'AI presets': 'AI presets',
    'API Key': 'API Key',
    'Request URL': 'Request URL',
    Model: 'Model',
    role: 'role',
    content: 'content',
    user: 'user',
    assistant: 'assistant',
    chat1: 'chat1',
    preset1: 'preset1',
    Hello: 'Hello',
    'How do you do?': 'How do you do?',
    key1: 'key1',
    '"value1"': '"value1"',
  },
  ja: {
    AI: 'AI',
    'Internet connected?': 'インターネットに接続していますか？',
    'Create a new chat with id[ID]': 'ID[ID]の新しいチャットを作成',
    'Delete chat with id[ID]': 'ID[ID]のチャットを削除',
    'Clear all chats': 'すべてのチャットをクリア',
    'Create a new AI preset with id [ID]': 'ID[ID]の新しいAIプリセットを作成',
    'Delete AI preset with id [ID]': 'ID[ID]のAIプリセットを削除',
    'Clear all AI presets': 'すべてのAIプリセットをクリア',
    'Set the [PROP] of AI preset [ID] to [VALUE]': 'AIプリセット[ID]の[PROP]を[VALUE]に設定',
    'Use AI preset [PRESET_ID] for chat [CHAT_ID]':
      'チャット[CHAT_ID]にAIプリセット[PRESET_ID]を使用',
    'Set request format for preset with id[ID] to [FORMAT]':
      'ID[ID]のプリセットのリクエスト形式を[FORMAT]に設定',
    'Send message [MESSAGE] to chat with id[ID]': 'ID[ID]のチャットにメッセージ[MESSAGE]を送信',
    'Stop message from chat [ID]': 'チャット[ID]のメッセージを停止',
    'Response from chat [ID]': 'チャット[ID]からの応答',
    'Status of chat with id[ID]': 'ID[ID]のチャットの状態',
    'Is chat with id[ID] idle?': 'ID[ID]のチャットはアイドル状態ですか？',
    'Common AI': '一般的なAI',
    'URL of [AI](Anthropic)': '[AI]のURL(Anthropic)',
    'URL of [AI](OpenAI)': '[AI]のURL(OpenAI)',
    'Data processing(JSON)': 'データ処理(JSON)',
    'Overwrite id[ID] in [MAP] with JSON [DATA]': 'JSON[DATA]で[MAP]のID[ID]を上書き',
    'Overwrite chat history of id[ID] with JSON [DATA]': 'JSON[DATA]でID[ID]のチャット履歴を上書き',
    'Clear chat history of id[ID]': 'ID[ID]のチャット履歴をクリア',
    'Add a message to chat [ID] with role[ROLE] and content[CONTENT]':
      'チャット[ID]にロール[ROLE]と内容[CONTENT]のメッセージを追加',
    'Delete message at index [INDEX] from chat with id[ID]':
      'ID[ID]のチャットからインデックス[INDEX]のメッセージを削除',
    'Cover [DIFF] to [BASE]': '[DIFF]を[BASE]に上書き',
    "Set [OBJECT]'s [KEY] to [VALUE]": '[OBJECT]の[KEY]を[VALUE]に設定',
    'All keys of [MAP]': '[MAP]のすべてのキー',
    'Data of [ID] from [MAP]': '[MAP]の[ID]のデータ',
    'Chat history from id[ID]': 'ID[ID]のチャット履歴',
    '[PROP] of item [INDEX] of chat history id[ID]':
      'チャット履歴ID[ID]の[INDEX]番目のアイテムの[PROP]',
    'Length of [ARRAY]': '[ARRAY]の長さ',
    'Item [INDEX] of array[ARRAY]': '配列[ARRAY]の[INDEX]番目のアイテム',
    'Item [KEY] of object[OBJECT]': 'オブジェクト[OBJECT]の[KEY]アイテム',
    Chats: 'チャット',
    'AI presets': 'AIプリセット',
    'API Key': 'APIキー',
    'Request URL': 'リクエストURL',
    Model: 'モデル',
    role: 'ロール',
    content: '内容',
    user: 'ユーザー',
    assistant: 'アシスタント',
    chat1: 'チャット1',
    preset1: 'プリセット1',
    Hello: 'こんにちは',
    'How do you do?': 'ごきげんいかがですか？',
    key1: 'キー1',
    '"value1"': '"値1"',
  },
  ko: {
    AI: 'AI',
    'Internet connected?': '인터넷에 연결되었나요?',
    'Create a new chat with id[ID]': 'ID[ID]로 새 채팅 만들기',
    'Delete chat with id[ID]': 'ID[ID]의 채팅 삭제',
    'Clear all chats': '모든 채팅 지우기',
    'Create a new AI preset with id [ID]': 'ID[ID]로 새 AI 프리셋 만들기',
    'Delete AI preset with id [ID]': 'ID[ID]의 AI 프리셋 삭제',
    'Clear all AI presets': '모든 AI 프리셋 지우기',
    'Set the [PROP] of AI preset [ID] to [VALUE]':
      'AI 프리셋 [ID]의 [PROP]을(를) [VALUE](으)로 설정',
    'Use AI preset [PRESET_ID] for chat [CHAT_ID]': '채팅 [CHAT_ID]에 AI 프리셋 [PRESET_ID] 사용',
    'Set request format for preset with id[ID] to [FORMAT]':
      'ID[ID] 프리셋의 요청 형식을 [FORMAT](으)로 설정',
    'Send message [MESSAGE] to chat with id[ID]': 'ID[ID] 채팅에 메시지 [MESSAGE] 보내기',
    'Stop message from chat [ID]': '채팅 [ID]의 메시지 중지',
    'Response from chat [ID]': '채팅 [ID]의 응답',
    'Status of chat with id[ID]': 'ID[ID] 채팅의 상태',
    'Is chat with id[ID] idle?': 'ID[ID] 채팅이 유휴 상태인가요?',
    'Common AI': '일반적인 AI',
    'URL of [AI](Anthropic)': '[AI]의 URL(Anthropic)',
    'URL of [AI](OpenAI)': '[AI]의 URL(OpenAI)',
    'Data processing(JSON)': '데이터 처리(JSON)',
    'Overwrite id[ID] in [MAP] with JSON [DATA]': 'JSON [DATA](으)로 [MAP]의 ID[ID] 덮어쓰기',
    'Overwrite chat history of id[ID] with JSON [DATA]':
      'JSON [DATA](으)로 ID[ID]의 채팅 기록 덮어쓰기',
    'Clear chat history of id[ID]': 'ID[ID]의 채팅 기록 지우기',
    'Add a message to chat [ID] with role[ROLE] and content[CONTENT]':
      '채팅 [ID]에 역할[ROLE]과 내용[CONTENT]의 메시지 추가',
    'Delete message at index [INDEX] from chat with id[ID]':
      'ID[ID] 채팅에서 인덱스 [INDEX]의 메시지 삭제',
    'Cover [DIFF] to [BASE]': '[DIFF]를 [BASE]에 덮어쓰기',
    "Set [OBJECT]'s [KEY] to [VALUE]": '[OBJECT]의 [KEY]을(를) [VALUE](으)로 설정',
    'All keys of [MAP]': '[MAP]의 모든 키',
    'Data of [ID] from [MAP]': '[MAP]의 [ID] 데이터',
    'Chat history from id[ID]': 'ID[ID]의 채팅 기록',
    '[PROP] of item [INDEX] of chat history id[ID]': '채팅 기록 ID[ID]의 [INDEX]번째 항목의 [PROP]',
    'Length of [ARRAY]': '[ARRAY]의 길이',
    'Item [INDEX] of array[ARRAY]': '배열[ARRAY]의 [INDEX]번째 항목',
    'Item [KEY] of object[OBJECT]': '객체[OBJECT]의 [KEY] 항목',
    Chats: '채팅',
    'AI presets': 'AI 프리셋',
    'API Key': 'API 키',
    'Request URL': '요청 URL',
    Model: '모델',
    role: '역할',
    content: '내용',
    user: '사용자',
    assistant: '어시스턴트',
    chat1: '채팅1',
    preset1: '프리셋1',
    Hello: '안녕하세요',
    'How do you do?': '처음 뵙겠습니다',
    key1: '키1',
    '"value1"': '"값1"',
  },
  fr: {
    AI: 'IA',
    'Internet connected?': 'Internet connecté ?',
    'Create a new chat with id[ID]': "Créer un nouveau chat avec l'ID[ID]",
    'Delete chat with id[ID]': "Supprimer le chat avec l'ID[ID]",
    'Clear all chats': 'Effacer tous les chats',
    'Create a new AI preset with id [ID]': "Créer un nouveau préréglage IA avec l'ID [ID]",
    'Delete AI preset with id [ID]': "Supprimer le préréglage IA avec l'ID [ID]",
    'Clear all AI presets': 'Effacer tous les préréglages IA',
    'Set the [PROP] of AI preset [ID] to [VALUE]':
      'Définir le [PROP] du préréglage IA [ID] sur [VALUE]',
    'Use AI preset [PRESET_ID] for chat [CHAT_ID]':
      'Utiliser le préréglage IA [PRESET_ID] pour le chat [CHAT_ID]',
    'Set request format for preset with id[ID] to [FORMAT]':
      "Définir le format de requête du préréglage avec l'ID[ID] sur [FORMAT]",
    'Send message [MESSAGE] to chat with id[ID]':
      "Envoyer le message [MESSAGE] au chat avec l'ID[ID]",
    'Stop message from chat [ID]': 'Arrêter le message du chat [ID]',
    'Response from chat [ID]': 'Réponse du chat [ID]',
    'Status of chat with id[ID]': "Statut du chat avec l'ID[ID]",
    'Is chat with id[ID] idle?': "Le chat avec l'ID[ID] est-il inactif ?",
    'Common AI': 'IA courantes',
    'URL of [AI](Anthropic)': 'URL de [AI](Anthropic)',
    'URL of [AI](OpenAI)': 'URL de [AI](OpenAI)',
    'Data processing(JSON)': 'Traitement des données(JSON)',
    'Overwrite id[ID] in [MAP] with JSON [DATA]': "Écraser l'ID[ID] dans [MAP] avec JSON [DATA]",
    'Overwrite chat history of id[ID] with JSON [DATA]':
      "Écraser l'historique du chat ID[ID] avec JSON [DATA]",
    'Clear chat history of id[ID]': "Effacer l'historique du chat ID[ID]",
    'Add a message to chat [ID] with role[ROLE] and content[CONTENT]':
      'Ajouter un message au chat [ID] avec le rôle[ROLE] et le contenu[CONTENT]',
    'Delete message at index [INDEX] from chat with id[ID]':
      "Supprimer le message à l'index [INDEX] du chat avec l'ID[ID]",
    'Cover [DIFF] to [BASE]': 'Couvrir [DIFF] vers [BASE]',
    "Set [OBJECT]'s [KEY] to [VALUE]": 'Définir [KEY] de [OBJECT] sur [VALUE]',
    'All keys of [MAP]': 'Toutes les clés de [MAP]',
    'Data of [ID] from [MAP]': 'Données de [ID] depuis [MAP]',
    'Chat history from id[ID]': "Historique du chat de l'ID[ID]",
    '[PROP] of item [INDEX] of chat history id[ID]':
      "[PROP] de l'élément [INDEX] de l'historique du chat ID[ID]",
    'Length of [ARRAY]': 'Longueur de [ARRAY]',
    'Item [INDEX] of array[ARRAY]': 'Élément [INDEX] du tableau[ARRAY]',
    'Item [KEY] of object[OBJECT]': "Élément [KEY] de l'objet[OBJECT]",
    Chats: 'Chats',
    'AI presets': 'Préréglages IA',
    'API Key': 'Clé API',
    'Request URL': 'URL de requête',
    Model: 'Modèle',
    role: 'rôle',
    content: 'contenu',
    user: 'utilisateur',
    assistant: 'assistant',
    chat1: 'chat1',
    preset1: 'préréglage1',
    Hello: 'Bonjour',
    'How do you do?': 'Comment allez-vous ?',
    key1: 'clé1',
    '"value1"': '"valeur1"',
  },
  es: {
    AI: 'IA',
    'Internet connected?': '¿Internet conectado?',
    'Create a new chat with id[ID]': 'Crear un nuevo chat con id[ID]',
    'Delete chat with id[ID]': 'Eliminar chat con id[ID]',
    'Clear all chats': 'Limpiar todos los chats',
    'Create a new AI preset with id [ID]': 'Crear un nuevo preset de IA con id [ID]',
    'Delete AI preset with id [ID]': 'Eliminar preset de IA con id [ID]',
    'Clear all AI presets': 'Limpiar todos los presets de IA',
    'Set the [PROP] of AI preset [ID] to [VALUE]':
      'Establecer [PROP] del preset de IA [ID] a [VALUE]',
    'Use AI preset [PRESET_ID] for chat [CHAT_ID]':
      'Usar preset de IA [PRESET_ID] para el chat [CHAT_ID]',
    'Set request format for preset with id[ID] to [FORMAT]':
      'Establecer formato de solicitud para preset con id[ID] a [FORMAT]',
    'Send message [MESSAGE] to chat with id[ID]': 'Enviar mensaje [MESSAGE] al chat con id[ID]',
    'Stop message from chat [ID]': 'Detener mensaje del chat [ID]',
    'Response from chat [ID]': 'Respuesta del chat [ID]',
    'Status of chat with id[ID]': 'Estado del chat con id[ID]',
    'Is chat with id[ID] idle?': '¿Está inactivo el chat con id[ID]?',
    'Common AI': 'IA comunes',
    'URL of [AI](Anthropic)': 'URL de [AI](Anthropic)',
    'URL of [AI](OpenAI)': 'URL de [AI](OpenAI)',
    'Data processing(JSON)': 'Procesamiento de datos(JSON)',
    'Overwrite id[ID] in [MAP] with JSON [DATA]': 'Sobrescribir id[ID] en [MAP] con JSON [DATA]',
    'Overwrite chat history of id[ID] with JSON [DATA]':
      'Sobrescribir historial de chat de id[ID] con JSON [DATA]',
    'Clear chat history of id[ID]': 'Limpiar historial de chat de id[ID]',
    'Add a message to chat [ID] with role[ROLE] and content[CONTENT]':
      'Añadir mensaje al chat [ID] con rol[ROLE] y contenido[CONTENT]',
    'Delete message at index [INDEX] from chat with id[ID]':
      'Eliminar mensaje en índice [INDEX] del chat con id[ID]',
    'Cover [DIFF] to [BASE]': 'Cubrir [DIFF] a [BASE]',
    "Set [OBJECT]'s [KEY] to [VALUE]": 'Establecer [KEY] de [OBJECT] a [VALUE]',
    'All keys of [MAP]': 'Todas las claves de [MAP]',
    'Data of [ID] from [MAP]': 'Datos de [ID] de [MAP]',
    'Chat history from id[ID]': 'Historial de chat de id[ID]',
    '[PROP] of item [INDEX] of chat history id[ID]':
      '[PROP] del elemento [INDEX] del historial de chat id[ID]',
    'Length of [ARRAY]': 'Longitud de [ARRAY]',
    'Item [INDEX] of array[ARRAY]': 'Elemento [INDEX] del array[ARRAY]',
    'Item [KEY] of object[OBJECT]': 'Elemento [KEY] del objeto[OBJECT]',
    Chats: 'Chats',
    'AI presets': 'Presets de IA',
    'API Key': 'Clave API',
    'Request URL': 'URL de solicitud',
    Model: 'Modelo',
    role: 'rol',
    content: 'contenido',
    user: 'usuario',
    assistant: 'asistente',
    chat1: 'chat1',
    preset1: 'preset1',
    Hello: 'Hola',
    'How do you do?': '¿Cómo está usted?',
    key1: 'clave1',
    '"value1"': '"valor1"',
  },
}

